docs_dir: /vagrant/notebook/
pages:
- [index.md, index]
- [flask study/ipython.md, ipython]
- ["flask study/\u8DEF\u7531\u89C4\u5219.md", "\u8DEF\u7531\u89C4\u5219"]
- [nginx study/chapter1.md, chapter1]
- [python study/chapter 1.md, chapter 1]
- [python study/context.md, context]
- [python study/descriptor.md, descriptor]
- [python study/mate.md, mate]
- [python study/parameter.md, parameter]
site_auther: 3b295
site_name: wiki
site_url: http://3b295.me
theme: readthedocs
