docs_dir: docs
pages:
- [index.md, index]
- ["flask/\u8DEF\u7531\u89C4\u5219.md", "\u8DEF\u7531\u89C4\u5219"]
- [flask/ipython.md, ipython]
- [nginx/nginx.md, nginx]
- [python/descriptor.md, descriptor]
- [python/context.md, context]
- [python/parameter.md, parameter]
- [python/mate.md, mate]
- ["python/\u57FA\u7840\u5E93.md", "\u57FA\u7840\u5E93"]
repo_url: https://github.com/3b295/3b295_wiki
site_auther: 3b295
site_dir: wiki
site_name: wiki
site_url: http://wiki.3b295.me
theme: readthedocs
